# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lipschitz/Documents/Code/C_Code/TYCam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lipschitz/Documents/Code/C_Code/TYCam/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lipschitz/Documents/Code/C_Code/TYCam/build/CMakeFiles /home/lipschitz/Documents/Code/C_Code/TYCam/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lipschitz/Documents/Code/C_Code/TYCam/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sample_common

# Build rule for target.
sample_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample_common
.PHONY : sample_common

# fast build rule for target.
sample_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sample_common.dir/build.make CMakeFiles/sample_common.dir/build
.PHONY : sample_common/fast

#=============================================================================
# Target rules for targets named TYCam

# Build rule for target.
TYCam: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TYCam
.PHONY : TYCam

# fast build rule for target.
TYCam/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TYCam.dir/build.make CMakeFiles/TYCam.dir/build
.PHONY : TYCam/fast

common/MatViewer.o: common/MatViewer.cpp.o

.PHONY : common/MatViewer.o

# target to build an object file
common/MatViewer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sample_common.dir/build.make CMakeFiles/sample_common.dir/common/MatViewer.cpp.o
.PHONY : common/MatViewer.cpp.o

common/MatViewer.i: common/MatViewer.cpp.i

.PHONY : common/MatViewer.i

# target to preprocess a source file
common/MatViewer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sample_common.dir/build.make CMakeFiles/sample_common.dir/common/MatViewer.cpp.i
.PHONY : common/MatViewer.cpp.i

common/MatViewer.s: common/MatViewer.cpp.s

.PHONY : common/MatViewer.s

# target to generate assembly for a file
common/MatViewer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sample_common.dir/build.make CMakeFiles/sample_common.dir/common/MatViewer.cpp.s
.PHONY : common/MatViewer.cpp.s

common/TYThread.o: common/TYThread.cpp.o

.PHONY : common/TYThread.o

# target to build an object file
common/TYThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sample_common.dir/build.make CMakeFiles/sample_common.dir/common/TYThread.cpp.o
.PHONY : common/TYThread.cpp.o

common/TYThread.i: common/TYThread.cpp.i

.PHONY : common/TYThread.i

# target to preprocess a source file
common/TYThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sample_common.dir/build.make CMakeFiles/sample_common.dir/common/TYThread.cpp.i
.PHONY : common/TYThread.cpp.i

common/TYThread.s: common/TYThread.cpp.s

.PHONY : common/TYThread.s

# target to generate assembly for a file
common/TYThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sample_common.dir/build.make CMakeFiles/sample_common.dir/common/TYThread.cpp.s
.PHONY : common/TYThread.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TYCam.dir/build.make CMakeFiles/TYCam.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TYCam.dir/build.make CMakeFiles/TYCam.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TYCam.dir/build.make CMakeFiles/TYCam.dir/main.cpp.s
.PHONY : main.cpp.s

tycamCapture.o: tycamCapture.cpp.o

.PHONY : tycamCapture.o

# target to build an object file
tycamCapture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TYCam.dir/build.make CMakeFiles/TYCam.dir/tycamCapture.cpp.o
.PHONY : tycamCapture.cpp.o

tycamCapture.i: tycamCapture.cpp.i

.PHONY : tycamCapture.i

# target to preprocess a source file
tycamCapture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TYCam.dir/build.make CMakeFiles/TYCam.dir/tycamCapture.cpp.i
.PHONY : tycamCapture.cpp.i

tycamCapture.s: tycamCapture.cpp.s

.PHONY : tycamCapture.s

# target to generate assembly for a file
tycamCapture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TYCam.dir/build.make CMakeFiles/TYCam.dir/tycamCapture.cpp.s
.PHONY : tycamCapture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TYCam"
	@echo "... sample_common"
	@echo "... common/MatViewer.o"
	@echo "... common/MatViewer.i"
	@echo "... common/MatViewer.s"
	@echo "... common/TYThread.o"
	@echo "... common/TYThread.i"
	@echo "... common/TYThread.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tycamCapture.o"
	@echo "... tycamCapture.i"
	@echo "... tycamCapture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

